/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mahernahlab (https://sketchfab.com/mahernahlab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/graduation-cap-pro-48291f7500eb4c34b881ba32bcff2d41
Title: Graduation Cap Pro
*/
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { GeneralGroupProps } from "../../utils/types";

export function GraduationCap(props: GeneralGroupProps) {
  const { nodes, materials } = useGLTF("/models/graduation_cap_pro.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder_Material001_0 as Mesh).geometry}
          material={materials["Material.001"]}
          position={[0, 100.861, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Sphere_Material003_0 as Mesh).geometry}
          material={materials["Material.003"]}
          position={[0, 96.262, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[16.455, 16.455, 8.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder001_Material001_0 as Mesh).geometry}
          material={materials["Material.001"]}
          position={[-109.833, 95.477, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.977, 0.972, 88.415]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder002_Material002_0 as Mesh).geometry}
          material={materials["Material.002"]}
          position={[-109.833, 88.596, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.977, 0.972, 88.415]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder003__0 as Mesh).geometry}
          material={materials["Cylinder.003__0"]}
          position={[-109.833, 95.477, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.977, 0.972, 88.415]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder004_Material001_0 as Mesh).geometry}
          material={materials["Material.001"]}
          position={[0, 100.861, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}
