/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MauroGonzalezA (https://sketchfab.com/MauroGonzalezA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-4b800e07ea3543e3870ad5e53b39d825
Title: Grass
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import { GeneralGroupProps } from '../../utils/types'

export function Grass(props: GeneralGroupProps) {
  const { nodes, materials } = useGLTF('/models/grass.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_4 as Mesh).geometry}
        material={materials.brush_Petal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_6 as Mesh).geometry}
        material={materials.brush_Petal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_8 as Mesh).geometry}
        material={materials.brush_Petal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_10 as Mesh).geometry}
        material={materials.brush_Petal}
      />
    </group>
  )
}