/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tomato Owl (https://sketchfab.com/tomato_owl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jelly-a59257e5fc344d0d9aca8187c7ade6fc
Title: Jelly
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";
import { Group, LoopRepeat, Mesh, SkinnedMesh } from "three";
import { SkeletonUtils } from "three-stdlib";
import { useGraph } from "@react-three/fiber";

export function Jelly(props) {
  const group = useRef<Group>(null);

  // Load GLB with animation baked in
  const { nodes, materials, animations } = useGLTF("/models/jelly.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && actions[animations[0]?.name]) {
      actions[animations[0].name]!
        .reset()
        .setLoop(LoopRepeat, Infinity)
        .play();
    }
  }, [actions, animations]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="27e3225649c445cdb3d6812a685ff94bfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_14"
                      geometry={(nodes.Object_14 as Mesh).geometry}
                      material={materials.blinn1}
                      skeleton={(nodes.Object_14 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_16"
                      geometry={(nodes.Object_16 as Mesh).geometry}
                      material={materials.sparkle1}
                      skeleton={(nodes.Object_16 as SkinnedMesh).skeleton}
                    />
                    <skinnedMesh
                      name="Object_18"
                      geometry={(nodes.Object_18 as Mesh).geometry}
                      material={materials.stars1}
                      skeleton={(nodes.Object_18 as SkinnedMesh).skeleton}
                    />
                    <group name="Object_13" />
                    <group name="Object_15" />
                    <group name="Object_17" />
                  </group>
                </group>
                <group name="Jelly" />
                <group name="sparkle" />
                <group name="stars" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/jelly.glb");
