/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/koala-from-poly-by-google-9ad5554ac9bd4c29a12a4911810658fb
Title: Koala from Poly by Google
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'

export function Koala(props) {
  const { nodes, materials } = useGLTF('/models/koala_from_poly_by_google.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_4 as Mesh).geometry}
        material={materials['455A64']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_5 as Mesh).geometry}
        material={materials.FFFFFF}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_6 as Mesh).geometry}
        material={materials['1A1A1A']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_7 as Mesh).geometry}
        material={materials.F06292}
      />
    </group>
  )
}

useGLTF.preload('/models/koala_from_poly_by_google.glb')
