/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: reiinaru (https://sketchfab.com/reiinaru)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pink-pudding-465c873020b04e658bf6caa759e7587f
Title: pink pudding
*/
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { GeneralGroupProps } from "../../utils/types";

export function PinkPudding(props: GeneralGroupProps) {
  const { nodes, materials } = useGLTF("/models/pink_pudding.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_4 as Mesh).geometry}
        material={materials["Material.001"]}
        position={[0, 1.234, 0]}
        scale={[1, 1.331, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_6 as Mesh).geometry}
        material={materials["Material.002"]}
        position={[-0.085, 3.097, -0.219]}
        rotation={[-0.39, 0.404, 0.16]}
        scale={[0.032, 0.093, 0.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_8 as Mesh).geometry}
        material={materials.Material}
        position={[-0.043, 2.831, -0.129]}
        rotation={[-0.39, 0.404, 0.16]}
        scale={0.417}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_10 as Mesh).geometry}
        material={materials.material_0}
        position={[0.399, 2.164, 0.106]}
        scale={0.789}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_12 as Mesh).geometry}
        material={materials["Material.003"]}
        scale={2.818}
      />
    </group>
  );
}


