/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dimal965 (https://sketchfab.com/dimal965)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sakura-c562e993e5ba411f8edd4b65ef0069d0
Title: sakura
*/
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { GeneralGroupProps } from "../../utils/types";

export function Sakura(props: GeneralGroupProps) {
  const { nodes, materials } = useGLTF("/models/sakura.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-100.419, 1682.519, -57.096]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Object001_mossybark02_0Mat_0 as Mesh).geometry}
            material={materials.mossybark02_0Mat}
            position={[-5246.426, -139.037, -1682.519]}
          />
        </group>
        <group
          position={[-311.737, 2156.01, -26.624]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              (nodes.Object002_sakura_branch_new01_1Mat_0 as Mesh).geometry
            }
            material={materials.sakura_branch_new01_1Mat}
            position={[-5005.651, -106.103, -2156.01]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/sakura.glb");
