/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: evolveduk (https://sketchfab.com/evolveduk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beech-tree-0983d8933531491f9be71c669e8a907b
Title: Beech tree
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/beech_tree.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Tree_0_Tree_0Mat_0 as Mesh).geometry}
          material={materials.Tree_0Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Tree_1_Tree_1Mat_0 as Mesh).geometry}
          material={materials.Tree_1Mat}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/beech_tree.glb')
